name: Generate Snake Animation

on:
  workflow_dispatch:  # permite rodar manualmente
  schedule:
    - cron: "0 0 * * *"  # roda 1x por dia

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Rikelme03
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Subir snake.svg no repositório
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: output
          folder: dist
